### ISSUE TITLE
Doesn't work on 1.15.2

### ISSUE THREAD

**Issue by TUCAOEVER** [YouHaveTrouble/CommandWhitelist#1]
Plugin doesn't work on 1.15.2 paper

**Comment by YouHaveTrouble** [comment]
Spigot page does say it's only been tested on 1.16. I will look into why it doesn't work on 1.15 later on today tho.

**Comment by YouHaveTrouble** [comment]
[v1.0.4](https://github.com/YouHaveTrouble/CommandWhitelist/releases/tag/v1.0.4) fixes this. Thankfully easy fix!
