### ISSUE TITLE
Custom Alias Not Working

### ISSUE THREAD

**Issue by yigityetkin** [YouHaveTrouble/CommandWhitelist#12]
For example, i have a custom alias for /cmi spawn command. It is /spawn. But when i add spawn command to whitelist, it is not working. Custom aliases are blocking from plugin.

**Comment by YouHaveTrouble** [comment]
Ah, I know exactly what are you talking about now. It's not a bug on my side, CMI aliases do not register as commands. Instead, they make player execute /cmi <subcommand>.

You can solve this by setting up aliases in bukkit's commands.yml and turning off CMI aliases.
There is literally no way for me to react to this type of plugin behavior.

You can find commands.yml in your main server directory, there should be an example of how aliases work :)

**Comment by yigityetkin** [comment]
Thank you very much bro <3 it worked.
