### ISSUE TITLE
hi, its me again :D

### ISSUE THREAD

**Issue by yigityetkin** [YouHaveTrouble/CommandWhitelist#13]
I fixed many command alias with your suggestion but only /cmi reply $1- command does not work.

I tried this way but its not working;

commands.yml

  r:
  - cmi reply $1-
  reply:
  - cmi reply $1-

**Comment by YouHaveTrouble** [comment]
Can you try testing with actual message in the command?
Like `/reply somethingsomething`?

I honestly don't know what goes through zrips' head when he does this crap. Try the full command, I know I had similiar situation with /cmi pay where I had to send all arguments for command to go through.

**Comment by YouHaveTrouble** [comment]
And again, this is something I can't fix from my side of things, as CMI command behavior is just unconventional and many would argue makes no sense, sorry.

**Comment by kforbro** [comment]
I made aliases of CMI commands in commands.yml, but tab complete arguments don't work for them. Is there any other way to make aliases?

**Comment by YouHaveTrouble** [comment]
> I made aliases of CMI commands in commands.yml, but tab complete arguments don't work for them. Is there any other way to make aliases?

I did indeed reproduce the issue. commands.yml is the go-to alias creation and the fact that cmi tab completions are not working indicate that they're most likely done incorrectly, just like commands. You can open a bug report about this for CMI, but I doubt zrips will do anything about it.

**Comment by kforbro** [comment]
I found a similar plugin that works fine with CMI aliases. Maybe you can take a look at it and fix the CommandWhitelist plugin?
https://www.spigotmc.org/resources/command-blocker-with-tabcomplete-removal.85719/

**Comment by kforbro** [comment]
I found a similar plugin that works with CMI aliases. Maybe you can take a look at it and fix it in your plugin?
https://www.spigotmc.org/resources/command-blocker-with-tabcomplete-removal.85719/

**Comment by YouHaveTrouble** [comment]
The plugin you sent doesn't really help, as it's closed source, and I see it works the other way around than CW, you have to list commands to block instead of commands to whitelist.

**Comment by kforbro** [comment]
> The plugin you sent doesn't really help, as it's closed source, and I see it works the other way around than CW, you have to list commands to block instead of commands to whitelist.
> 
> Edit: Well, maybe some more explanation is in order.
> When you have a list of commands you whitelist, you need to properly detect those commands to allow them. By doing this other way around you only need to detect commands you do not allow. This doesn't fix the issue you presented, which is cmi not properly handling aliases and tab completions for them, you're just hiding the problem.
> 
> This issue is 100% on CMI's side.

You are slightly mistaken. The plugin I sent works the same way as CommandWhitelist. It blocks all commands that are not in the list.

I looked at the plugin code through the decompiler and found out that it uses packetlistener instead of playercommandsendevent. As far as I understand, this is why the commandblocker plugin works with CMI aliases.
https://hastebin.com/igocaxewuk.typescript

**Comment by YouHaveTrouble** [comment]
You appear to be partly right.
Listening to command packet does work as you say. Then again, I want to emphasize that it still IS cmi's issue.
I will add a config option to the next build to use protocollib, it will be opt-in, as it's not needed for 99% of cases.

**Comment by YouHaveTrouble** [comment]
Option added in [newest build](https://github.com/YouHaveTrouble/CommandWhitelist/releases/tag/v1.7.0).
