### ISSUE TITLE
Commands with //

### ISSUE THREAD

**Issue by kforbro** [YouHaveTrouble/CommandWhitelist#17]
the first case:
`commands:
  default:
    - wand`
The //wand command works, but tab complete doesn't work

the second case:
`commands:
  default:
    - /wand`
The //wand command doesn't work, but tab complete does

`use-protocollib-to-detect-commands: true`

**Comment by YouHaveTrouble** [comment]
Reproduced, will take a look what's happening there

**Comment by YouHaveTrouble** [comment]
Ok, did some debugging, make sure you:
- Have permission for //wand
- Have added `/wand` to the list (this will add `//wand`, as the list skips the first `/`)

![image](https://user-images.githubusercontent.com/6951472/110123163-d70bce00-7dc0-11eb-8034-49593fe40880.png)

I don't know how you got /wand to work with a single `/`, it's literally not a command in worldedit.

**Comment by kforbro** [comment]
![image](https://user-images.githubusercontent.com/39985355/110308452-2d6f4b80-8011-11eb-9f5e-c05c953b03ca.png)

![image](https://user-images.githubusercontent.com/39985355/110308508-40821b80-8011-11eb-95bc-87330070baf2.png)

**Comment by YouHaveTrouble** [comment]
What version of the plugin are you using?
Do you have any other plugins that handle commands on your server?
Can you reproduce with just CW and WE on the server?

**Comment by YouHaveTrouble** [comment]
Stale issue, assumin problem was fixed on user's side.
