### ISSUE TITLE
It would nice to add a command to reload config file

### ISSUE THREAD

**Issue by TUCAOEVER** [YouHaveTrouble/CommandWhitelist#2]
Any plan to add a command to reload config file? It would be much easier to add new whitelist command

**Comment by YouHaveTrouble** [comment]
Will add on my todo list for this plugin! ^^

**Comment by YouHaveTrouble** [comment]
Added in [v1.1.0](https://github.com/YouHaveTrouble/CommandWhitelist/releases/tag/v1.1.0)!
