### ISSUE TITLE
Compatibility with Purpur?

### ISSUE THREAD

**Issue by CroaBeast** [YouHaveTrouble/CommandWhitelist#20]
Hello, I want to ask if the plugin is compatible with Purpur.

I use Purpur version git-Purpur-1051 (MC: 1.16.5) and with CommandWhitelist 1.7.3 but the tab completion and the whitelist doesn't work on any way.

Do you want some logs, config, or anything related? Or is the plugin not compatible with Purpur?

**Comment by YouHaveTrouble** [comment]
Plugin is fullly compatible with Purpur, I personally use it on Purpur.
Make sure o check out [FAQ](https://github.com/YouHaveTrouble/CommandWhitelist/wiki/FAQ) and see if you're doing everything correctly.

**Comment by CroaBeast** [comment]
I check that and I was doing correctly.

I use LuckPerms to give the default group the permission: "commandwhitelist.commands.default"

This is my config.yml: 
`messages:
  prefix: "&8[&e&lCMW&8] "
  command-denied: "&cNo puedes usar este comando."
  subcommand-denied: "&cNo puedes usar este argumento para ese comando."
  no-permission: "&cNo tienes permiso para hacer esto."
  no-such-subcommand: "&cNo existe este argumento."
  config-reloaded: "&eConfiguration reloaded."
  added-to-whitelist: "&eWhitelisted command &6%s &efor permission &6%s"
  removed-from-whitelist: "&eRemoved command &6%s &efrom permission &6%s"
  group-doesnt-exist: "&cGroup doesn't exist or error occured"

# To cover the 1% of plugins that don't register their commands and/or aliases properly.
# Do not enable if you don't have issues with aliased commands.
# This requires server restart to take effect.
use-protocollib-to-detect-commands: true

commands:
  # Permissions that control what commands players can use
  # you can add unlimited amount of whitelists

  # this will be automatically given to players by default
  default:
    - ps
    - tpa
    - tpaccept
    - tpacancel
    - tpahere
    - back
    - rtp
    - afk
    - tienda
    - gifts
    - recompensas
    - boost
    - stars
    - buy
    - discord
    - kit
    - marry
    - duel
    - mypet
    - pets
    - pvp
    - servato
    - sermorra
    - spawn
    - newenchants
    - starsoff
  # commandwhitelist.commands.example
  vip:
    - condense
    - suicide
    - nick
    - dispose
    - glow
  mvp:
    - anvil
    - hat
    - craft
    - head
  pro:
    - ec
    - itemname
  pub:
    - repair
    - flightcharge
    - flyc
    - nick
  helper:
    - invsee
    - tp
    - prueba
  mod:
    - co
    - fly
    - gms
    - gmsp
    - vanish
    - v

tabcompletions:
  # This one is working as a blacklist. Player will not be able
  # to see/use listed subcommands unless they have specified permission
  # commandwhitelist.subcommands.example
  example:
    - help about
`

**Comment by YouHaveTrouble** [comment]
You don't need to grand default permission for some time now.

I also still don't know what exactly is your issue, as you didn't describe it in a way that it can't be taken in multiple contexts.

**Comment by CroaBeast** [comment]
The issue is that all the commands are denied by the plugin, and I can't see the custom tab completion, I see all the plugins instead of the custom one

**Comment by YouHaveTrouble** [comment]
Are there any errors printed at startup?
are things working fine with default config?

**Comment by CroaBeast** [comment]
No errors when the server starts.
And no, even with a new config it doesn't work as should.

**Comment by YouHaveTrouble** [comment]
If you have any other plugins messing with commands, please try removing them

**Comment by YouHaveTrouble** [comment]
You can also try addin a command to default whitelist via `/cw add` , that will basically refresh the config, if that errors out it means something's wrong with the config

**Comment by CroaBeast** [comment]
This is my plugin list:

```Plugins (61): AnnouncerPlus, AutoPluginLoader, BannerBoard*, BeeHivesTrees, BetterRTP, BungeeGuard, BuycraftX, CAM*, ChestSort, Citizens, CleanroomGenerator, CMI, CMILib, CommandPanels, ConsoleSpamFix, CoreProtect, CustomJoinMessages*, DeathMessages, DiscordSRV, Duels, eco, EcoEnchants, EnderPearlFix, EntityTrackerFixer, HolographicDisplays, HolographicExtension, InfiniteScoreboard, InfoHeads, ItemEdit, ItemTag, LastLoginAPI, LevelPoints, LuckPerms, Marriage, MessageEditor, Multiverse-Core, Multiverse-Inventories, MyCommand, MyPet, MySQLNicks, OreAnnouncer, PlaceholderAPI, ProtectionStones, ProtocolLib, QueuedCommands*, RawMsg, RemoteCommands*, SAML, SkinsRestorer, TransparentHeads, Vault, VeinMiner, ViaBackwards, ViaRewind, ViaVersion, VillagerOptimiser, VoidSpawn, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags```

**Comment by YouHaveTrouble** [comment]
I literally cannot tell what your plugins do based on names and I don't have the time to check them one by one. This basically doesn't help. Try running commandWhitelist without plugins, if it works, another plugin is interfering with it. That's all.

**Comment by YouHaveTrouble** [comment]
latest version of CW works on my testing server, which is latest purpur. Cannot reproduce your issue locally.

**Comment by CroaBeast** [comment]
yisus, well, I'm gonna try that with a backup server

**Comment by CroaBeast** [comment]
Ok... this is weird. My backup server works with the plugin, but the original no, I cannot understand why
