### ISSUE TITLE
ViaVersion+ViaBackwards compatibility issue

### ISSUE THREAD

**Issue by polonytzer** [YouHaveTrouble/CommandWhitelist#21]
Greetings.
I run a PaperMC 1.16.5 server with ViaVersion-3.2.1 + ViaBackwards-3.2.0.
When using 1.16.5, CommandWhitelist works flawlessly as expected.

**Describe the bug**
But if I use Minecraft 1.12.2, open the chat, type `/` and then press `TAB`, it shows all the server commands, including the ones that normal players without permissions couldn't use.

**Expected behavior**
Commands shouldn't be displayed for users without permission.

**To Reproduce**
1. Login using Minecraft 1.12.2
2. Open chat in the server, type `/`, and then press `TAB`
3. It'll appear all the commands of the server (related image below).

**Screenshots**
![bug](https://user-images.githubusercontent.com/82187612/114631905-de61a980-9c93-11eb-91f9-5a685b3e3e61.png)

**Additional context**
- Happens with all users without OP permission
- A issue was opened on ViaBackwards repo, but the fix couldn't solve 100% de issue and some commands are still appearing (Link for the issue: https://github.com/ViaVersion/ViaBackwards/issues/328).

**Comment by YouHaveTrouble** [comment]
I can check paper's tab complete event, but that still doesn't solve the problem completely, that's the nature of how protocol hacks work.

**Comment by YouHaveTrouble** [comment]
Actually, upon closer inspection, the fix was merged into dev version of viabackwards, so I guess you can try getting a dev build from them. This is not a CommandWhitelist issue per se and I don't really want to implement a workaround for something that should be fixed on viabackwards end.

**Comment by YouHaveTrouble** [comment]
Seems to be fixed on ViaBackwards' end [here](https://github.com/ViaVersion/ViaBackwards/pull/353).
