### ISSUE TITLE
can you add the ability to display commands from a plugin called worldedit?-  //set //replace //wand ...

### ISSUE THREAD

**Issue by jocker505** [YouHaveTrouble/CommandWhitelist#22]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by YouHaveTrouble** [comment]
Well, that's not how you use issues, but I think I know what you mean. It's already possible to do. Just add commands that you want to add and ommit one of the slashes.
So if you want to add "//wand", you need to add "/wand" in the config.
