### ISSUE TITLE
Command beginnings still visible with utility mods aka "hacked clients"

### ISSUE THREAD

**Issue by Crepesman** [YouHaveTrouble/CommandWhitelist#30]
**Is your feature request related to a problem? Please describe.**
Yes. The problem is that players can still see the plugin list using the _.plugins_ command on utility mods such as Meteor. This is closely related to commands, as commandless plugins are not shown. 

**Describe the solution you'd like**
I'm not super knowledgeable on this but I think there is a packet, or multiple ones, that the plugin should be cancelling.

**Describe alternatives you've considered**
Look into ProtocolLib stuff is my guess.

**Additional context**
Just to confirm, the "hacks" are able to tell command arguments beginnings, hence displaying the "plugin list". What I mean is "minecraft:", "essentials:" etc. Another conclusible thing is that they are able to display server brand command beginnings as well, such as "paper:", "purpur:" etc.

I switched from a plugin that's similar to this one, and they're asking users to purchase the premium version of it to be able to block _.plugins_.
Implementing a workaround seems very possible to do since there are multiple servers that are successful at blocking _.plugins_, so it would be really nice if you figured it out.

**Comment by YouHaveTrouble** [comment]
CW was never meant to block plugin list. The goal is to only display commands that players can use to them for more professionall and less chaotic look. I consider this to be out of scope of the plugin. However, if anyone's willing to PR that does this, sure, why not.

**Comment by YouHaveTrouble** [comment]
See if [2.0-ALPHA-3](https://github.com/YouHaveTrouble/CommandWhitelist/releases/tag/v2.0.0-ALPHA-3) fixes this. Afaik it should.

**Comment by YouHaveTrouble** [comment]
In my testing 2.0 versions take care of this issue.
