### ISSUE TITLE
/help h bypassing "h" subcommand tabcompletions

### ISSUE THREAD

**Issue by Tavies** [YouHaveTrouble/CommandWhitelist#32]
**Describe the bug**
It would be really amazing to have a wildcard modifier for the subcommand tabcompletion section so /help * would block all subcommands for that. I've typed out every single subcommand so only /help shows up however /help help and /help helpop still show up for tab completion, and when typing /help h it will show a list of all "h" subcommands even though they are normally blocked.

**Expected behavior**
Block all tab completions/subcommand tabcompletions. Ease of use for blocking multiple subcommands with wildcard.

**To Reproduce**
Paper 1.17 and CW1.7.7 (luckperms, vault etc)

**Screenshots**
![cwissue1](https://user-images.githubusercontent.com/78396492/124261621-dde3ec80-dae5-11eb-99a3-cda931e9f278.png)
![cwissue2](https://user-images.githubusercontent.com/78396492/124261618-dd4b5600-dae5-11eb-8aa0-bf0cfec9c8d3.png)

**Comment by YouHaveTrouble** [comment]
I really like the wildcard idea, will probably be implemented in 2.0
I'm not sure why subcommands still display for some commands,will take a look into that today.

**Comment by YouHaveTrouble** [comment]
bug fixed in [1.7.8](https://github.com/YouHaveTrouble/CommandWhitelist/releases/tag/v1.7.8)
I'm gonna open a separate issue regarding feature request for the * wildcard

**Comment by Tavies** [comment]
Thank you again for the help!
