### ISSUE TITLE
Colorization failure when using MiniMessage in CommandWhitelist v2.0.0-ALPHA-1

### ISSUE THREAD

**Issue by 4drian3d** [YouHaveTrouble/CommandWhitelist#34]
**Describe the bug**
When I try to use MiniMessage and test its use in the console, the message is displayed without the color

**Expected behavior**
Messages are colored correctly

**To Reproduce**
1. Start a Velocity 3.0.0 server (I don't think this is the cause of the error).
2. Install CommandWhitelist v2.0.0-ALPHA-1 on Velocity
3. Configuring plugin messages using [MiniMessage](https://docs.adventure.kyori.net/minimessage.html#format)
4. When using "/vcw reload" in console, the message will be displayed incorrectly.

**Screenshots**
![fallo](https://user-images.githubusercontent.com/68704415/124612010-976cf580-de37-11eb-9479-f62a0579623c.png)

**Additional context**
I have tried the command "/vcw add (group) (command)" and the corresponding message is displayed "correctly" _(There is color, but it cuts like a client version <1.15.)_
It seems that the problem is only in the command "/vcw reload".

**Comment by YouHaveTrouble** [comment]
Fixed in [alpha-2](https://github.com/YouHaveTrouble/CommandWhitelist/releases/tag/v2.0.0-ALPHA-2).
Thanks for reporting!
