### ISSUE TITLE
This plugin doesn't work on paper 1.16.2

### ISSUE THREAD

**Issue by sergyops** [YouHaveTrouble/CommandWhitelist#4]
i'm using 3 servers: bungeecord, spigot 1.12.2 and paper 1.16.2 and this plugin hides bungee commands on spigot server but not on paper

**Comment by YouHaveTrouble** [comment]
You need to use waterfall to block bungee command completions, 1.12 version uses protocolib, that's why 1.12 works. Waterfall is drag and drop replacement for bungeecord.
Here's link for waterfall download https://papermc.io/downloads#Waterfall
