### ISSUE TITLE
Bungeecord support

### ISSUE THREAD

**Issue by srnyx** [YouHaveTrouble/CommandWhitelist#44]
**Is your feature request related to a problem? Please describe.**
The only plugin that has Bungeecord (and Spigot) anti-tab complete support costs $8

**Describe the solution you'd like**
Support for Bungeecord

**Describe alternatives you've considered**
Buying the $8 plugin or not having anti-tab complete for Bungeecord commands

**Comment by YouHaveTrouble** [comment]
It's impossible to do without huge hacky workarounds.
Bungeecord lacks the event for tab completion.
Please use waterfall. Seriously. Bungee sucks.

**Comment by YouHaveTrouble** [comment]
If you wish to discuss this further, you're welcome to do so on my discord
