### ISSUE TITLE
Do I need to install on both proxy + Bukkit?

### ISSUE THREAD

**Issue by srnyx** [YouHaveTrouble/CommandWhitelist#45]
If not, will I lose any features if I don't install it on both?

**Comment by YouHaveTrouble** [comment]
If you want to block proxy commands/completion, you need the plugin on proxy.
If you want to block bukkit commands/completions, you need the plugin on bukkit.

**Comment by srnyx** [comment]
> If you want to block proxy commands/completion, you need the plugin on proxy. If you want to block bukkit commands/completions, you need the plugin on bukkit.

So putting it on just the proxy and inputting a Bukkit command won't do anything?

**Comment by YouHaveTrouble** [comment]
> So putting it on just the proxy and inputting a Bukkit command won't do anything?

If it blocked that command, that would be confusing as hell, wouldn't it?
Imagine troubleshooting that with someone that wouldn't be aware of that. Bukkit version blocks bukkit commands, proxy version blocks proxy commands, makes sense and is predictible.

**Comment by srnyx** [comment]
> > So putting it on just the proxy and inputting a Bukkit command won't do anything?
> 
> If it blocked that command, that would be confusing as hell, wouldn't it? Imagine troubleshooting that with someone that wouldn't be aware of that. Bukkit version blocks bukkit commands, proxy version blocks proxy commands, makes sense and is predictible.

Alright, thank you!
