### ISSUE TITLE
Making command in list of allowed command only apply to it, no subcommands

### ISSUE THREAD

**Issue by TheJoshue** [YouHaveTrouble/CommandWhitelist#48]
Will you consider making that if we define `help` it'll allow us to ONLY use `/help` not `/help anything1`?
If we want to allow ANY subcommand as another arg, we define `help *` as allowed, that will allow us to execute `/help anything1` but not `/help anything1 anything2`?
Please consider this because there are still vulnerabilities if you have big complex of plugins (a lot of plugins) or custom stuff, this is very neat

Thank you for developing this.

**Comment by YouHaveTrouble** [comment]
That would be quite counterintuitive, you would expect `/tpo YouHaveTrouble` to work when you whitelist `/tpo`.
There is a plan to introduce a wildcard for subcommand filter that will let you block all subcommands, but the proposal you made is not fit for default behavior.

**Comment by TheJoshue** [comment]
any chance then you'll add for `subcommands` section ability to use `command *` to prevent any subcommand (2nd arg) from being executed, while if we want to allow specific one, we list it in above list of allowed commands as `command allowedsubcommand`?

**Comment by YouHaveTrouble** [comment]
To be completely honest I'm still looking for a way to do exactly  what you want wihout being overcomplicated.
At this point in time I'm looking to rework how subcommand section works to accomodate both scenarios, but for now I'm lacking ideas on how to actually accomplis this.

**Comment by TheJoshue** [comment]
I understand and I am happy my idea (actually my thought) is useful to you.
I not that good in coding so I can't help there, although i want to make a little note to you here

I wasn't using your plugin until I discovered (few days ago) that your plugin makes ability to use it on a server which has ViaVersion and expands support for (for example) from 1.8 to 1.18

Your plugin works only for 1.13+ servers, so let's say we host 1.16.5 server.

In this case, anyone who join with 1.8-1.12 will indeed be able to tab complete ONLY defined commands from your plugin.

This is something (from my very deep research for some time) very rare and i hope you'll keep this in mind and KEEP this functionality (so if you mess this up in some update and somebody (probably i will first) tests it and it's not working as before, we'll report and you'll try to bring back this feature)

Thank you for your time!

**Comment by YouHaveTrouble** [comment]
I cannot guarantee it will keep working for <1.13 clients, this relies a lot on how via/protocolsupport/similiar plugins handle that.
As long as those handle things properly, it should work just fine.
