### ISSUE TITLE
Command doesn't work with default config

### ISSUE THREAD

**Issue by VictorGamer15** [YouHaveTrouble/CommandWhitelist#50]
**Describe the bug**
When I try to use /vcw with the default config, it shows an error in console.

**Expected behavior**
I expected to use the command without any issues.

**To Reproduce**
1. Download Velocity 3.1.2 (git-b3fc8e82-b118)
2. Load CommandWhitelist
3. Use the /vcw command

**Screenshots**
![imagen](https://user-images.githubusercontent.com/69861104/158987345-ca0b5935-12c2-4514-8161-0d203df2a1fe.png)

**Additional context**
I haven't updated my proxy in a while, maybe I'm outdated.

**Comment by YouHaveTrouble** [comment]
Try newest version. should be fixed.
