### ISSUE TITLE
Protocolib console error

### ISSUE THREAD

**Issue by Zoiter7** [YouHaveTrouble/CommandWhitelist#52]
I installed the latest version of plugin for Paper 1.19, using the Bukkit one release, I activated the Protocolib setting in the config, and seems is broken, I get this error on the console when tabbing.

https://www.toptal.com/developers/hastebin/rasetelopu.rb

**Comment by YouHaveTrouble** [comment]
https://github.com/dmulloy2/ProtocolLib/issues/1646
Protocollib issue.

**Comment by YouHaveTrouble** [comment]
Reopening because it's still relevant and easier to find as open

**Comment by YouHaveTrouble** [comment]
I just ended up dropping entire command list send on packet level functionality. It gets rid of the error and I can't be bothered to figure out what was actually wrong with it.
That means that command list will be only modified by the api. If someone was nuts enough to inject their commands via a packet, good lord, run away from that plugin asap.
