### ISSUE TITLE
Automatic whitelist

### ISSUE THREAD

**Issue by xFreakss** [YouHaveTrouble/CommandWhitelist#55]
**Describe the solution you'd like**
Would be nice to have an option to allow tab completion only for the commands that the player has permission to use

**Comment by YouHaveTrouble** [comment]
This entire issus is why CW exists at all.
Imagine a world where if player does not have permission to the command, that command does not tabcomplete.
This is our world. this is default command behavior in minecraft. The thing breaking that behavior are plugin developers who refuse to register command permissions properly. You're right, it would be nice if they did. The reality is that they don't and there is no reliable way to tell how they implemented permission check for their command.
