### ISSUE TITLE
Group Problem

### ISSUE THREAD

**Issue by AquaWoid** [YouHaveTrouble/CommandWhitelist#56]
First of all, thanks for making this plugin it's rly awesome and saved me alot of pain! So i've created a group called "admin" inside the config.yml which should be corresponding to my "admin" group inside of the Luckperms permission manager. If i've got that right from the wiki these two groups are supposed to be working with each other. My problem is that the commands (even if permitted through LP) are not showing up for the Char with the "admin" group. The command will only show up if i put them in the "default" group in the config.yml (even if the admin group isn't set to inherit "default"'s permissions through LP) and set the corresponding permissions to the "admin" group. So all in all, my "admin" group isn't doing anything, i mean i could leave it completely blank and just manage the visibility through permissions and putting the commands in the "default" group but that's not exactly an elegant way to do it. Hope i could describe my problem understandably. I think it's most likely a problem on my end, but maybe you're able to help me.. Thanks in advance though!!
Here is the config as .txt (as github doesnt support yml) 
[config.txt](https://github.com/YouHaveTrouble/CommandWhitelist/files/9274773/config.txt)

**Comment by YouHaveTrouble** [comment]
Default group is not assigned to any permission. It's *default*, automatically applied to everyone without permission check.
CW groups also don't magically apply to permission plugin groups, you need to grant `commandwhitelist.group.<group_name>` permission to the luckperms group that you want the CW group to apply.

**Comment by AquaWoid** [comment]
Ohhh i see, that's the part that i was missing! Huge thanks for the reply and keep up the good work! :)
