### ISSUE TITLE
Can I run OP command without OP？

### ISSUE THREAD

**Issue by NeoxyCN** [YouHaveTrouble/CommandWhitelist#57]
I mean if it is possible for this plugin to do that.
Like I don not have op, but I can use /tp.
It seems that it is impossible for Velocity Plugin to do that.
Thank you.

**Comment by YouHaveTrouble** [comment]
I'm extremely confused about what you're asking.
What does velocity have to do with op command?

**Comment by NeoxyCN** [comment]
> I'm extremely confused about what you're asking. What does velocity have to do with op command?
Sorry I use vanilla server for fully redstone functions without permission control， so I want to use velocity to do that.
Unfortunately I found it seems that I coud not control players(without OP permission)' command when they use OP's commands, such as /tp /ban

**Comment by NeoxyCN** [comment]
> I'm extremely confused about what you're asking. What does velocity have to do with op command?

Sorry I use vanilla server for fully redstone functions without permission control， so I want to use velocity to do that.
Unfortunately I found it seems that I coud not control players(without OP permission)' command when they use OP's commands, such as /tp /ban

**Comment by YouHaveTrouble** [comment]
Of course not, proxy plugin only handles proxy commands. If you want to handle backend commands, sadly you need a plugin on the backend server.
Although you can switch to fabric and use luckperms for that as you would on bukkit-based server https://luckperms.net/download. You can control permissions like that

**Comment by NeoxyCN** [comment]
> Of course not, proxy plugin only handles proxy commands. If you want to handle backend commands, sadly you need a plugin on the backend server. Although you can switch to fabric and use luckperms for that as you would on bukkit-based server https://luckperms.net/download. You can control permissions like that

Thanks
Oh, I see.
I will start working on fabric.
To be honest, some redstone "features" are not available in bukkit-based server.
Thank you very much.
