### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by diszeey** [YouHaveTrouble/CommandWhitelist#6]
Hi,
thanks for fix tab completion but still i see spam in console. (1.12.2)
![image](https://user-images.githubusercontent.com/73243246/96767921-7a91ae80-13dd-11eb-9b15-0f0a68d580a7.png)

**Comment by YouHaveTrouble** [comment]
redownload the latest release, should be fixed

**Comment by diszeey** [comment]
Great. Thanks ^^
