### ISSUE TITLE
Option to whitelist an entire plugin

### ISSUE THREAD

**Issue by LaserSlime** [YouHaveTrouble/CommandWhitelist#60]
**Is your feature request related to a problem? Please describe.**
Basically I want to make a group for my builder rank that has access to all worldedit commands and I don't want to paste in all the worldedit commands seperately.

**Describe the solution you'd like**
A way to whitelist the commands of an entire plugin.

**Describe alternatives you've considered**
A blacklist option would also work. Maybe just add an option to make the existing lists work as blacklists instead of whiltelists?

**Comment by YouHaveTrouble** [comment]
If that was possible, it would be a thing.
there is no reliable way to get what plugin command belongs to afaik.

You can use `/cw dump` to get list of all available commands and copy the list from there, that's the best workaround available.
