### ISSUE TITLE
[Bug Report] Error when using \ in command

### ISSUE THREAD

**Issue by D3adhkwen** [YouHaveTrouble/CommandWhitelist#61]
**Describe the bug**
Error shows in console when the character `\` is used in command.

**Expected behavior**
Console should not output any error

**To Reproduce**
1. Use `\` in command, for example: /home\
2. Check error in console

**Logs**
https://pastebin.com/MgSPuFhQ

**Additional context**
Pufferfish 1.19.2 Build 35
CommandWhitelist 2.5.2

**Comment by Pantera07** [comment]
reproducible

**Comment by Pantera07** [comment]
This command also throws an error.
```
/?
/\
/(
/)
/$
/*
/+
```

**Comment by YouHaveTrouble** [comment]
Fixed in [v2.5.3](https://github.com/YouHaveTrouble/CommandWhitelist/releases/tag/v2.5.3)
