### ISSUE TITLE
CommandWhitelist is not blocking commands anymore.

### ISSUE THREAD

**Issue by Dagrond** [YouHaveTrouble/CommandWhitelist#62]
Since update 2.5.0 CommandWhitelist is not blocking non-whitelisted commands anymore. They are not highlighted (so the client says "Unknown or incomplete command"), but after sending it, the command is executed properly. Any release before 2.5.0 works as it should.

**Comment by YouHaveTrouble** [comment]
Not enough information.
Which version? velocity? waterfall? bukkit?
Protocollib enabled or not?
Also send your config.

**Comment by YouHaveTrouble** [comment]
Closing, not enough information provided
