### ISSUE TITLE
Suggestion: semi-whitelist

### ISSUE THREAD

**Issue by cantorthiagofelipe** [YouHaveTrouble/CommandWhitelist#63]
I'm using the CW and I'm really enjoying it, but I ran into a situation and would like to suggest an addition.

I notice that when creating a custom command (an alias) I need to whitelist both the custom command and the original (so the function can run).
The player can view both commands in tabcompleter.

I wanted to suggest a new section in the config, something like "semi whitelist", in which the player DOESN'T SEE THE COMMAND IN THE TABCOMPLETER, but manages to execute the command anyway.

e.g.
original - /locate biome plains
custom alias - /plains

whitelist:
- plains
semi-whitelist:
- locate biome plains

In this situation, the player only sees "/plains" but is able to execute both commands

**Comment by YouHaveTrouble** [comment]
> I need to whitelist both the custom command and the original
You're not creating an alias then. you're just making server force execute command as player. Create proper alias in commands.yml or register the alias properly if you're speaking from plugin dev's perspective.
