### ISSUE TITLE
[Feature Request] List of commands that need confirmation to send

### ISSUE THREAD

**Issue by RhythmicSys** [YouHaveTrouble/CommandWhitelist#64]
I'm not certain that this is in the scope of this project, but it seemed similar enough that I wanted to attempt a FR anyways

I think it'd be nice to be able to make a list of commands that need user confirmation in order to run
I know plugins sometimes do this on their own, but many do not

so it could be like
```yaml
require confirmation:
  - trust all
  - untrust all
  - kill 
  - op
```
or something to that effect
and it'd be like `Are you sure you want to kill @e`?

**Comment by YouHaveTrouble** [comment]
Not in scope, although interesting and potentially useful enough to become a standalone plugin in the future
