### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by goosBanny** [YouHaveTrouble/CommandWhitelist#65]
**Describe the bug**
https://bin.birdflop.com/uxelinesiq.rb ClassCastException occurs.

**Expected behavior**
Plugin should load up normally.

**Additional context**
Pufferfish Build 1.19.3 #54
Config: https://bin.birdflop.com/uriluxijew.yaml

**Comment by YouHaveTrouble** [comment]
It's a mistake in your config.
`subcommands: {}`
subcommands is a list, not a map. I should be `[]` instead of `{}`
