### ISSUE TITLE
CW does not support case sensitivity

### ISSUE THREAD

**Issue by holenyt** [YouHaveTrouble/CommandWhitelist#66]
Command /hub working, but /HuB or /Hub - not working.
Only lower case working.
Same with other commands.

**Comment by YouHaveTrouble** [comment]
If lowercase is working, then I consider this a low prio.
System currently in place would require many changes to accomodate to one or two people tYpInG lIkE tHaT

**Comment by YouHaveTrouble** [comment]
If I get to it. Like I said, it's a low priority issue

**Comment by HoLeNYT** [comment]
Thanks

**Comment by YouHaveTrouble** [comment]
you're supposed to keep issue open until it gets resolved ^^

**Comment by YouHaveTrouble** [comment]
At the time of me writing this, the current behavior is actually working as intended as [vanilla commands are case sensitive](https://bugs.mojang.com/browse/MC-523) and the standard of creating commands is all-lowercase string.
