### ISSUE TITLE
Reload Command doesn't work

### ISSUE THREAD

**Issue by CroaBeast** [YouHaveTrouble/CommandWhitelist#7]
Hello, I want to reload the plugin in FlameCord but it doesn't work. Says: `'>....=>.... [15:08:31 INFO]: Command not found'`
Do I need a permission to do it in game or what is the correct command to reload the config in FlameCord?

And if I put two groups or more, all the commands of those groups will be appear in the tablist?

Besides, I don't see if the plugin has commands to execute, like /commandwhitelist /cw or something like that

**Comment by YouHaveTrouble** [comment]
The command for bungeeecord version is "/bcw". It has to be that way in case you got the plugin on both bungee and spigot servers, if it was the same you wouldn't be able to reload spigot config. Hope that clears things up! :)

**Comment by CroaBeast** [comment]
Thanks, but it will be really helpfull if you add the reload command in the spigot page, and the permission for that in the wiki.
Good plugin btw, thanks again.
