### ISSUE TITLE
Update for 1.20

### ISSUE THREAD

**Issue by DressyLemon** [YouHaveTrouble/CommandWhitelist#71]
Love this plugin! Please update for 1.20 as it is not currently working

**Comment by YouHaveTrouble** [comment]
"not working" doesn't tell me anything. Please include server logs with the error you're getting.

**Comment by DressyLemon** [comment]
Absolutely Sorry mate! The issue was saying that it did not support the latest bukkit version. It has been working after your update!

Thanks for the amazing plugin again!
