### ISSUE TITLE
Plugin does not allow you to edit config and always sets default values

### ISSUE THREAD

**Issue by Overwrite987** [YouHaveTrouble/CommandWhitelist#72]
**Describe the bug**
If you try to change the config somehow (adding new commands/changing plugin messages), the plugin still sets the default configuration.

**Expected behavior**
Changes to the message and available commands when changing the config

**To Reproduce**
1. Install plugin (latest version)
2. Strat the server
3. Change values in config.
4. do /cw reload or restart the server
5. check your confugiration. it will be default one

**Screenshots**
nan

**Additional context**
nan

**Comment by YouHaveTrouble** [comment]
Already looking into it, thanks for the report!

**Comment by YouHaveTrouble** [comment]
Fixed in [2.8.1](https://github.com/YouHaveTrouble/CommandWhitelist/releases/tag/v2.8.1)
