### ISSUE TITLE
[BUG] Skript’s permission message shows up.

### ISSUE THREAD

**Issue by JeffreyRCGithub** [YouHaveTrouble/CommandWhitelist#73]
**Describe the bug**
The bug is where if you do a skript command it will not just show the no such command thing and will show the skript’s permission message too.

**Expected behavior**
You shouldn’t see skript’s permission message.
**To Reproduce**
1. Download Skript from their github.
2. Put Skript's .jar file into the plugins folder.
3. Restart the server.
4. Now make a file named test.sk in /plugins/Skript/scripts/.
5. Put this text into the file:
command test:
[2 spaces here]permission: permission.test
[2 spaces here]trigger:
[4 spaces here]message "test" to player
6. Do the command /test. Make sure you do NOT have op or have the permission permission.test.
7. It will send the configured no such command but it also sends skript's permission message.
 **Screenshots**

**Additional context**

**Comment by YouHaveTrouble** [comment]
If this is the case, skript is ignoring the command cancellation state. You can use protocollib mode to stop the command before it's processed by the server. There's nothing other plugins can do when skript just decides to send their message anyway regardless of event cancellation.
