### ISSUE TITLE
Only Tab-Commands are blocked

### ISSUE THREAD

**Issue by MinecraftNight4** [YouHaveTrouble/CommandWhitelist#75]
**Describe the bug**
The commands can be auto-completed, but i can run it:
![image](https://github.com/YouHaveTrouble/CommandWhitelist/assets/42017416/afe09850-1fcb-4a4f-83a7-7cf9773b24f0)
![image](https://github.com/YouHaveTrouble/CommandWhitelist/assets/42017416/7b02b421-bae3-4e97-a555-b78abf9b8db9)

**Expected behavior**
I remember using this plugin in earlier versions, because it was able to whitelist commands and tab-command list.

**Server Info:**
git-Purpur-2004 (MC: 1.20.1)
CommandWhitelist version 2.8.1

**Comment by YouHaveTrouble** [comment]
This just looks like you don't have the permission for the command itself. CW does not replace permissions, it's a layer on top of existing ones.

**Comment by YouHaveTrouble** [comment]
are you op or have bypass permission?

**Comment by MinecraftNight4** [comment]
Nope, i just have default perms:
![image](https://github.com/YouHaveTrouble/CommandWhitelist/assets/42017416/4cbad413-a7c4-4902-a88c-34df1825d8e0)

And the default perms only affects Skin Restorer:
![image](https://github.com/YouHaveTrouble/CommandWhitelist/assets/42017416/7335a708-de83-48d6-996c-ff7ef7c79dcd)

**Comment by YouHaveTrouble** [comment]
can you disable protocollib mode and restart?

**Comment by MinecraftNight4** [comment]
It's working!
Thanks!!

**Comment by YouHaveTrouble** [comment]
Give me your protocollib version while you're at it, you're the second person that reports disabling that hook fixes the issue, so I'd like to investigate
