### ISSUE TITLE
Fabric compat?

### ISSUE THREAD

**Issue by Nicolol1234** [YouHaveTrouble/CommandWhitelist#76]
**Is your feature request related to a problem? Please describe.**
Not compaticle with a modded environment

**Describe the solution you'd like**
a fabric compatible version

**Describe alternatives you've considered**
Didn't found any :(

**Comment by Nicolol1234** [comment]
pretty sure it will be rejected but at least i tried

**Comment by YouHaveTrouble** [comment]
It's unlikely this will ever happen. Mod loaders don't really have unified command api and the very nature of frequent updates in fabric and having to of push new version each snapshot would introduce way too much maintenance burden. Bukkit, waterfall and velocity have stable APIs allowing the plugin to work without the need of updates every time version changes, fabric mods however require recompiling for each version
