### ISSUE TITLE
Whitelist commands doesnt work

### ISSUE THREAD

**Issue by Oskury** [YouHaveTrouble/CommandWhitelist#78]
**Describe the bug**

Hi! I created menus with DeluxeMenus and the custom commands that it creates, for example /selector, are blocked by commandwhitelist even if they are added to the whitelist to be unlocked..

**Expected behavior**
its clear only what i said

**To Reproduce**
its clear only what i said

**Screenshots**
its clear only what i said

**Additional context**
its clear only what i said

**Comment by YouHaveTrouble** [comment]
invalid issue, no reproduction steps provided
