### ISSUE TITLE
tab complete blocker bug

### ISSUE THREAD

**Issue by xsorencoolx** [YouHaveTrouble/CommandWhitelist#79]
hey so on client 1.8.9 if player try to tab complete it show all commands but on higher client only commands that i set will show i use CommandWhitelist-Velocity-2.8.1 jar

**Comment by YouHaveTrouble** [comment]
version 1.8 is not supported. If you have any issues with it it's on the software you use to allow it to connect.
Plugin supports 1.13+ due to massive changes to command system since that version
