### ISSUE TITLE
Default messages

### ISSUE THREAD

**Issue by shaqupl** [YouHaveTrouble/CommandWhitelist#8]
I'm using CommandWhitelist-1.3.3 and ProtocolLib v4.6.0 -SNAPSHOT-b482 and git-Paper-253 (MC: 1.16.3).
The problem is the default messages that cannot be changed.
Previous versions was fine.

**Comment by YouHaveTrouble** [comment]
Hello, can you try to regenerate the config? (just make a copy and delete the file from plugins directory). See if default config has the same issue.

**Comment by YouHaveTrouble** [comment]
Also, you do not need protocolib on 1.13+ ;)

**Comment by YouHaveTrouble** [comment]
Cannot reproduce. This is probably a mistake in your config if the values are being defaulted.
Try validating your config here https://yamlvalidator.com/ and see if there are any errors.

This may be because you used " or ' in one of the lines.

**Comment by YouHaveTrouble** [comment]
As this didn't get a response for a week I assume the issue was resolved. If you still have issues feel free to open another issue :)
