### ISSUE TITLE
cw doesnt see cmd

### ISSUE THREAD

**Issue by xgodstolbik** [YouHaveTrouble/CommandWhitelist#80]
Sorry, my english lvl low.

I'm faced with such a problem that the plugin doesn't see the command

Screen - https://spigotmc.ru/attachments/config-copy-yml.22193/

Configuration- 
![Uploading 1706709399763.png…]()

**Comment by YouHaveTrouble** [comment]
Screenshot you provided is behind a login wall on a random website I don't really want to register on and the configuration link appears to be a failed attempt of uploading a png file. Configuration is a text file, not a picture.

**Comment by xgodstolbik** [comment]
![image](https://github.com/YouHaveTrouble/CommandWhitelist/assets/158496916/468bedb4-e6d6-458a-9643-d8a89e4247b1)

**Comment by YouHaveTrouble** [comment]
It's possible that the plugin you use is forcing the player to execute another (possibly full) command. You'll have to find out which command is forcefully executed and whitelist it itself, or, more properly, alias the command properly yourself using commands.yml
