### ISSUE TITLE
SUBCOMMAND BUG

### ISSUE THREAD

**Issue by HonzasikCZ** [YouHaveTrouble/CommandWhitelist#81]
**Describe the bug**
I added only one to the players' subcommands that I didn't want the players to be able to write, and to the helpers' subcommands I added two subcommands that are intended for the players so that the helpers can't write them, but if I give them to them, the players now won't be able to write them either... player group in luckperms have nothing to do with group helpers.

**Expected behavior**
the two subcommands(ucc confess and ucc contact) should work for the players, but they don't

**To Reproduce**
groups:
  helper:
    commands:
    - ucc
    subcommands:
    - ucc confess
    - ucc contact
  default:
    commands:
    - ucc
    subcommands:
    - ucc reload

**Screenshots**
helper view of commands:
![obrazek](https://github.com/YouHaveTrouble/CommandWhitelist/assets/94143975/30e8d0cf-5c40-4524-ba8c-427dbd65a6df)
player view of commands (nothing is here):
![obrazek](https://github.com/YouHaveTrouble/CommandWhitelist/assets/94143975/1994994d-26c3-44cb-9221-712be14cb50f)

**Additional context**
I can't think of anything else

**Comment by YouHaveTrouble** [comment]
Create a separate group for subcommands and deny the permission for it for helper group
