### ISSUE TITLE
CommandWhitelist ignore custom commands from Skript

### ISSUE THREAD

**Issue by MisterLolxd2** [YouHaveTrouble/CommandWhitelist#82]
**Describe the bug**
CommandWhitelist ignore custom commands from Skript?

Simple: I have in skript custom command like /VIP if i execute this command without any permission i see: https://i.imgur.com/4b1FuB7.png
Information "No such command" but command was executed...

CommandWhitelist Version: 2.8.2
Server Version: Purpur 1.19.4 
Dump from CommandWhitelist: https://pastebin.com/AyNiKEKe (in dump we can see custom command from skript like /vip)
Config: default

Weird happend in default config of commandwhitelist players can use "warp" but if i used the "warps" command was executed.

**Expected behavior**
Block custom commands.

**Comment by YouHaveTrouble** [comment]
how are you adding the command in skript?

**Comment by MisterLolxd2** [comment]
Like this:

command /vip:
	trigger:
		execute console command "chestcommands open vip.yml %player%"

**Comment by YouHaveTrouble** [comment]
Only thing I can think of is the command you execute on console forces player to execute an additional command

**Comment by MisterLolxd2** [comment]
This would mean that event cancellation of command is bypassed. But by what?
At the moment, this command is not included in the command whitelist, just like other commands that I have in the Skript and commandwhitelist sees them, but does not effectively cancel them.

**Comment by YouHaveTrouble** [comment]
I can't reproduce.

**Comment by YouHaveTrouble** [comment]
Can't reproduce the issue. I'm assuming there's an issue on your setup.
