### ISSUE TITLE
It's possible to allow command but not tab-complete it?

### ISSUE THREAD

**Issue by msmanui** [YouHaveTrouble/CommandWhitelist#83]
So i would like command **/test** to be usable but not auto-complete. ¿It's possible? If not, would you consider add it? It would be useful for secnearios where i give awards to player that need to be executed as player, so i don't want to autocomplete

**Comment by YouHaveTrouble** [comment]
No. Basically any scenario that requires this is an instance of security through obscurity, which is extremely bad practice. Seek alternatives.

**Comment by YouHaveTrouble** [comment]
There's no reason to not show that command to the player then. If they can click it at any time, they can also execute it, therefore they should be able to see that they can. I'm not having this discussion for a millionth time.

**Comment by msmanui** [comment]
Displaying commands that are only used in events and requiring players to click to join serves to keep a clean Tab complete and present a good image for the server.
It's not all about "they should be able to see that they can."

**Comment by gecko10000** [comment]
I've implemented this in [my fork](https://github.com/gecko10000/CommandWhitelist).
