### ISSUE TITLE
Command lock does not work properly in 1.20.4

### ISSUE THREAD

**Issue by ChrisTVH** [YouHaveTrouble/CommandWhitelist#87]
When I use it with ProtocolLib, it simply does not work, even though I have added the commands to the list, the autocomplete of the commands does not appear that is fine, but the commands do execute.

When I use it without ProtocolLib, the commands are not executed, not even the commands that are in the list are executed, sometimes they are executed but the little message that you put by default when the commands are blocked appears.

The steps to reproduce are simple, first have ProtocolLib 5.2.0 or higher, have this version of the server:
![image](https://github.com/YouHaveTrouble/CommandWhitelist/assets/58376852/f1d4405f-e200-4f0f-a283-2fb1705cb2ec)

Just in case, my list of plugins:
![image](https://github.com/YouHaveTrouble/CommandWhitelist/assets/58376852/06fe2c77-4d7c-481d-9fd8-757925d591ba)

If more information is required I will be happy to provide it, as additional information, I have this plugin on both my proxy and backend servers.
As to whether any errors appear in the console, I have not seen any.
Versions used: CommandWhitelist-Bukkit-2.8.2 and CommandWhitelist-Velocity-2.8.1.

**Comment by YouHaveTrouble** [comment]
Yes, this is exactly why I say it every time, if you don't need to enable it, don't enable it. it's not "better" to do this on packet level. I will have to look into removing protocollib feature entirely as plugins that needed it either died or now allow to create aliases in commands.yml

**Comment by ChrisTVH** [comment]
> Yes, this is exactly why I say it every time, if you don't need to enable it, don't enable it. it's not "better" to do this on packet level. I will have to look into removing protocollib feature entirely as plugins that needed it either died or now allow to create aliases in commands.yml

You mean this is happening because of that?
I have two plugins that use ProtocolLib, Lib's Disguises and ItemsAdder.

But otherwise it's as you say, no one else uses it.

**Comment by YouHaveTrouble** [comment]
I mean it in CW's case. It's not "better" to handle commands on the packet level. Just disable it in the config unless it's absolutely necessary.

**Comment by ChrisTVH** [comment]
> I mean it in CW's case. It's not "better" to handle commands on the packet level. Just disable it in the config unless it's absolutely necessary.

Sip, solo que no me sirve de ninguna de las dos formas :/

**Comment by YouHaveTrouble** [comment]
I'm closing this with a resolution that it's an issue specific to your setup.
It's literally not possible for cw to block tab completion, but not execution. There is only one list for both features. One working and second not working can only mean something else is interfering.
