### ISSUE TITLE
[Feature Request] Guice 7.0.0 Compatibility

### ISSUE THREAD

**Issue by R00tB33rMan** [YouHaveTrouble/CommandWhitelist#88]
Is Guice 7.0.0 compatibility planned at any point? Although some differences are futile, I do believe that integrating compatibility has some level of importance in the future, as there may come a day where Velocity itself happens to upgrade to Guice 7.0.0, which may effectively break CommandWhitelist for a duration.

**Comment by 4drian3d** [comment]
> may come a day where Velocity itself happens to upgrade to Guice 7.0.0, which may effectively break CommandWhitelist

*what*

**Comment by R00tB33rMan** [comment]
> How would that break it?

Utilizing Guice 7.0.0 makes CommandWhitelist fail to start, as I’m assuming it’s simply incompatible at this time; however, I was just merely mentioning this if it were to be a possibility. Is it not? I didn’t think that this was too far fetched. I don’t have any expectations here; however, I thought it’d be worth mentioning.

Example: https://mclo.gs/8WiDFWh

**Comment by 4drian3d** [comment]
> > may come a day where Velocity itself happens to upgrade to Guice 7.0.0, which may effectively break CommandWhitelist
> 
> *what*
> 
> 

https://github.com/YouHaveTrouble/CommandWhitelist/blob/master/CommandWhitelistVelocity%2Fsrc%2Fmain%2Fjava%2Feu%2Fendermite%2Fcommandwhitelist%2Fvelocity%2FCommandWhitelistVelocity.java#L23 ah, yes, javax annotations

**Comment by YouHaveTrouble** [comment]
Okay, what would be the fix then

**Comment by R00tB33rMan** [comment]
> Okay, what would be the fix then

Fixed in #89
