### ISSUE TITLE
The tab blocker does not working in 1.16.4.

### ISSUE THREAD

**Issue by KoxSosen** [YouHaveTrouble/CommandWhitelist#9]
The plugin is installed under a waterfall fork called firefly.

The 1.12 hub with protocollib:

![image](https://user-images.githubusercontent.com/67807644/99518135-7632c400-2990-11eb-8f8d-2531ee2b7bb6.png)

The 1.16.4 Tunity latest build server:
![image](https://user-images.githubusercontent.com/67807644/99518197-8b0f5780-2990-11eb-90cb-ccf5163f8b97.png)

The servers are connected to the same bungee.

**Comment by YouHaveTrouble** [comment]
Cannot reproduce. Make sure that:
- Plugin is installed on your spigot servers
- You do not have op or * permission

**Comment by KoxSosen** [comment]
I'm not op, and the plugin isn't installed on the backend servers.

**Comment by YouHaveTrouble** [comment]
You Have to have the plugin on the backend servers if you want to block spigot commands

**Comment by KoxSosen** [comment]
Uh, thank you! Let me install it quick in the backend servers.

**Comment by YouHaveTrouble** [comment]
That being said, you gave me an idea, not sure how about actual inner workings of it now, but I might try doing something similiar to what you thought would work ;)

**Comment by KoxSosen** [comment]
![image](https://user-images.githubusercontent.com/67807644/99526542-af246600-299b-11eb-9174-778b7f23e877.png)

Still doesn't works, I'm not oppend, and the plugin is installed in the backend, as well as waterfall.

**Comment by KoxSosen** [comment]
![image](https://user-images.githubusercontent.com/67807644/99526660-d7ac6000-299b-11eb-8642-fd5d1819405c.png)

**Comment by YouHaveTrouble** [comment]
did you restart the server?

**Comment by KoxSosen** [comment]
yes.

**Comment by KoxSosen** [comment]
Issue fixed, wrong console.

**Comment by YouHaveTrouble** [comment]
Can you see if it errored in any way while starting up?
Also make sure your pemission group does not contain commandwhitelist.bypass or just *

**Comment by KoxSosen** [comment]
![image](https://user-images.githubusercontent.com/67807644/99526871-32de5280-299c-11eb-9b09-c3bfa5f1ddaa.png)

**Comment by YouHaveTrouble** [comment]
That's a configuration error. Did you change anything in the config file?

**Comment by KoxSosen** [comment]
Yes, thank you, the plugin now works as expected, and it's amazing!
