### ISSUE TITLE
[Feature Request] Placeholder that returns the command as text

### ISSUE THREAD

**Issue by Qui143** [YouHaveTrouble/CommandWhitelist#90]
**Is your feature request related to a problem? Please describe.**
I'm trying to compose a vanilla error message using the mini-message format, but I'm having difficulty because there's a missing placeholder.

**Describe the solution you'd like**
example:

Enter: /asd
message > asd is a non-existent command!

**Describe alternatives you've considered**
Adding the %command% placeholder looks good.

**Additional context**

**Comment by YouHaveTrouble** [comment]
added for bukkit and waterfall in [2.9.0]( https://github.com/YouHaveTrouble/CommandWhitelist/releases/tag/v2.9.0)

**Comment by jd07159** [comment]
I think it would be better to add this placeholder to `subcommand_denied` as well.
