### ISSUE TITLE
Leaking tab completions for 1.12.2 for Velocity

### ISSUE THREAD

**Issue by whiler-sesame** [YouHaveTrouble/CommandWhitelist#92]
**Describe the bug**
Not whitelisted tab completions are still sent to 1.12.2 client on Velocity when completing from "/", not from partially typed text.

**Expected behavior**
It should be blocked.

**To Reproduce**
1. Install Velocity version.
2. Join with 1.12.2 client.
3. Try to complete from "/" command.

**Additional context**
Might be related to #91

**Comment by YouHaveTrouble** [comment]
1.12 is not one of the supported versions. My honest tip would be to not allow versions as old as that on. Clients s older than 1.13 also cannot support velocity's modern forwarding.
