### ISSUE TITLE
How to make it work across cluster

### ISSUE THREAD

**Issue by older-fox** [YouHaveTrouble/CommandWhitelist#93]
I currently have a Velocity server with plugins installed within it. I would like to configure it to grant different command access permissions to different groups, such as:

Players have default permissions for 20 commands on server A, 5 commands on server B, and 10 commands on server C.
All other commands will be block by this plugin

beside install this plugin on three different servers, A, B, C, is there any other way to let it work?

**Comment by YouHaveTrouble** [comment]
By design, CW only works on a server it's installed on. It would be a nightmare to debug if proxies interfered with the backend server commands.

**Comment by older-fox** [comment]
> By design, CW only works on a server it's installed on. It would be a nightmare to debug if proxies interfered with the backend server commands.

Thanks for reply, I decide to install into all servers and use LP to sync all the permissions.

**Comment by older-fox** [comment]
Issue closed
