### ISSUE TITLE
HOW CAN I ADD ALL WE COMMANDS?

### ISSUE THREAD

**Issue by HonzasikCZ** [YouHaveTrouble/CommandWhitelist#96]
Hello!

I would like to ask how to add all the worldedit commands..I tried a few things but none of them worked and I certainly wouldn't want to write all the commands to a file.

**Comment by YouHaveTrouble** [comment]
You can't without listing the ones you want to add. There is no way to identify what plugin added a command after it was registered. If there was, you bet it would be a feature.
